"""
Joseph Lin
CMSC 437

This program scores the tagged sense output generated BY wsd.py, comparing it
to the gold standard answers provided in the line-key file. It determines the overall accuracy
and produces a confusion matrix.

Usage:
python scorer.py my-line-answers.txt line-key.txt

The program prints:
- The overall accuracy (percentage of correctly tagged instances)
- A confusion matrix showing counts of predicted versus gold senses.

"""

import sys
from lxml import etree
from collections import defaultdict

def parse_answers(file_path):
    """
    Parses XML in a file containing <answer> tags using lxml.
    The XML content is preprocessed, removing any problematic characters, stripping extra whitespace, and wrapping the content in a root element.
    Returns a dictionary mapping the instance id to sense.
    """
    with open(file_path, 'r', encoding='utf-8-sig', errors='replace') as f:
        data = f.read().strip()
    #Remove problematic null characters like 0x0.
    data = data.replace('\x00', '')
    #The content is wrapped in a root element.
    wrapped_data = "<answers>" + data + "</answers>"
    root = etree.fromstring(wrapped_data)
    
    answers = {}
    for answer in root.xpath('.//answer'):
        instanceId = answer.get('instance')
        sense = answer.get('senseid')
        answers[instanceId] = sense
    return answers

def main():

    #Input files
    pred_file = sys.argv[1]
    key_file = sys.argv[2]
    
    #Parse predicted and gold answers using lxml.
    predictions = parse_answers(pred_file)
    gold = parse_answers(key_file)
    
    total = 0
    correct = 0
    #Construct a confusion matrix: gold sense > predicted sense > count
    confusion = defaultdict(lambda: defaultdict(int))
    
    for instanceId, gold_sense in gold.items():
        predicted_sense = predictions.get(instanceId, "None")
        total += 1
        if predicted_sense == gold_sense:
            correct += 1
        confusion[gold_sense][predicted_sense] += 1
    
    accuracy = (correct / total) * 100
    print(f"Accuracy: {accuracy:.2f}% ({correct} out of {total} correct)\n")
    print("Confusion Matrix (rows: gold, columns: predicted):")
    
    #Collect the senses from both gold and predictions
    all_senses = set()
    for gs in confusion:
        all_senses.add(gs)
        for ps in confusion[gs]:
            all_senses.add(ps)
    all_senses = sorted(all_senses)
    
    header = "Gold\\Pred".ljust(12) + "".join(s.ljust(12) for s in all_senses)
    print(header)
    for gs in all_senses:
        row = gs.ljust(12)
        for ps in all_senses:
            row += str(confusion[gs].get(ps, 0)).ljust(12)
        print(row)

if __name__ == "__main__":
    main()
